from django.db import models
import datetime


# Create your models here.

class ToolbarVersion(models.Model):
    version  = models.CharField(max_length = 100) #2.3.1
    injection_code = models.CharField(max_length = 100)

class Users(models.Model):
    user_id = models.CharField(max_length = 50) #Generated by toolbar and sent on each request
    install_date = models.DateTimeField()
    browser_list = models.CharField(max_length = 100)
    OS = models.CharField(max_length = 100)
    IP = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100)
    country = models.CharField(max_length = 100)
    active = models.BooleanField()
    force_uninstall = models.BooleanField()
    toolbar_version = models.ForeignKey(ToolbarVersion)

class VisitLog(models.Model):
    page_url = models.CharField(max_length = 300)
    domain = models.CharField(max_length = 100)
    date_time = models.DateTimeField()
    user_id = models.ForeignKey(Users)
    browser = models.CharField(max_length = 100)
    IP = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100)
    country = models.CharField(max_length = 100)

class SearchEngineQueryLog(models.Model): #This will store all the search results on google, yahoo, bing, etc
    search_engine = models.CharField(max_length = 100)
    user_id = models.ForeignKey(Users)
    query = models.CharField(max_length = 100)
    visit_id = models.ForeignKey(VisitLog) #Has reference to visitLog

class AdContainer(models.Model):
    dimension = models.CharField(max_length = 100)
    container_base_url = models.CharField(max_length = 100) #The base url that the admin can create for each container dimension

class AdServedLog(models.Model):
    visit_id = models.ForeignKey(VisitLog)
    container_url = models.CharField(max_length = 100) #Unique url generated for the current user's page request contain/id/ip/etc
    container_id = models.ForeignKey(AdContainer)

class Niche(models.Model):
    url_pattern = models.CharField(max_length = 100)
    name = models.CharField(max_length = 100)

class Affiliate(models.Model):
    affiliate_id = models.CharField(max_length = 100)
    user_id = models.ForeignKey(Users)
    active = models.BooleanField()


class dummy_data(models.Model):
    val1 = models.CharField(max_length = 500)
    val2 = models.CharField(max_length = 500)
    val3 = models.CharField(max_length = 500)
    val4 = models.CharField(max_length = 100)
    val5 = models.CharField(max_length = 100)
    val6 = models.CharField(max_length = 100)
    val7 = models.CharField(max_length = 100)

#Do we need any more tables to track number of clicks to each domain on a daily basis?